version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: svg-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: svg-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always